version: '3'

services:
  app_server:
    build:
        context: .
        dockerfile: ./Dockerfile
    tty: true
    container_name: sgroup-be
    ports:
      - "5000:3308"
    volumes:
      - ./:/src/app
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

    environment: 
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=140903
      - DB_NAMEDBSGROUP=sgroupbe
      - PORT_NODEJS=3306
      - SECRET='nyann'
      - SMTP_HOST="smtp.gmail.com"
      - SMPT_PORT=587
      - SMTP_USER="phanthithanhnhan1409@gmail.com"
      - SMTP_PASS="ajrgyssofenxemxs"
    networks:
      - sgroup-network
  mysql:
    image: mysql:8.0
    container_name: app-sql
    restart: 'always'
    environment:
      MYSQL_ROOT_PASSWORD: 140903
      MYSQL_DATABASE: sgroupbe
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    ports:
      - 3307:3306
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - sgroup-network

  redis:
    image: 'redis:6.0.5-alpine'
    container_name: app-redis
    command: redis-server
    ports:
      - 6379:6379
    restart: 'always'
    volumes:
      - ./docker/redis/data:/var/lib/redis
    networks:
      - sgroup-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

networks:
  sgroup-network: